# Generated by Django 5.1.6 on 2025-04-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # This migration is empty because a City app existed before
        # It is now deleted, the migration is remaining
        # in order to not break the graph,
        ("user", "0001_initial"),
    ]

    operations = []
