# Generated by Django 5.1.6 on 2025-10-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_city_name_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
