# Generated by Django 5.1.6 on 2025-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_remove_rate_reviewer_rate_owner_alter_rate_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
