# Generated by Django 5.1.6 on 2025-04-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('puzzle', '0002_rename_published_puzzle_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puzzles', to='brand.brand', null=True),
        ),
    ]
