# Generated by Django 5.1.6 on 2025-04-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('puzzle', '0003_alter_puzzle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puzzles', to='brand.brand'),
        ),
    ]
