# Generated by Django 5.1.6 on 2025-04-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('puzzle', '0004_alter_puzzle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puzzles', to='category.category'),
        ),
    ]
