# Generated by Django 5.1.6 on 2025-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_puzzle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puzzle_images/'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='condition',
            field=models.CharField(choices=[('new', 'available'), ('used', 'used'), ('damaged', 'damaged')]),
        ),
    ]
