# Generated by Django 5.1.6 on 2025-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_remove_puzzle_image_url_puzzle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
