# Generated by Django 5.1.6 on 2025-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_alter_puzzle_description_alter_puzzle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('swapped', 'swapped'), ('deleted', 'deleted')], default='available'),
        ),
    ]
