# Generated by Django 5.1.6 on 2025-09-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_alter_puzzle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
