# Generated by Django 5.1.6 on 2025-10-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('puzzle', '0009_puzzle_height_puzzle_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='category',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='categories',
            field=models.ManyToManyField(related_name='puzzles', to='category.category'),
        ),
    ]
