# Generated by Django 5.1.6 on 2025-10-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('puzzle', '0010_remove_puzzle_category_puzzle_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
