# Generated by Django 5.1.6 on 2025-10-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0011_puzzle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='category',
        ),
    ]
