# Generated by Django 5.1.6 on 2025-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0012_remove_puzzle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('damaged', 'damaged')]),
        ),
    ]
