# Generated by Django 5.1.6 on 2025-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('exchange_request', "Demande d'échange"), ('new_message', 'Nouveau message'), ('exchange_accepted', 'Echange accepté'), ('exchange_denied', 'Echange refusé')], max_length=50),
        ),
    ]
