# Generated by Django 5.1.6 on 2025-08-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_exchange_message'),
        ('message', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='exchange',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='exchange.exchange'),
            preserve_default=False,
        ),
    ]
