# Generated by Django 5.1.6 on 2025-02-15 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('ravensburger', 'Ravensburger'), ('clementoni', 'Clementoni'), ('jan van Haasteren', 'Jan van Haasteren'), ('gibsons', 'Gibsons'), ('educa', 'Educa'), ('schmidt Spiele', 'Schmidt Spiele'), ('buffalo Games', 'Buffalo Games'), ('wasgij', 'Wasgij'), ('puzzle Master', 'Puzzle Master'), ('eurographics', 'Eurographics')])),
                ('piece_count', models.IntegerField()),
                ('description', models.TextField(max_length=3000)),
                ('condition', models.CharField(choices=[('available', 'available'), ('used', 'used'), ('damaged', 'damaged')])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('swap', 'swap')], default='available')),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
