# Generated by Django 5.1.6 on 2025-02-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='published',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
