# Generated by Django 5.1.6 on 2025-02-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('puzzle', '0002_rename_published_puzzle_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='requester',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle.puzzle'),
        ),
    ]
