# Generated by Django 5.1.6 on 2025-04-11 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_exchange_puzzle_exchange_puzzle_asked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='requester',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_asked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
