# Generated by Django 5.1.6 on 2025-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_exchange_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
